/**
 * Minimal INSEM (insem/0.2) model for an element type that has no `definitionYaml` in the GCS catalog,
 * built from the catalog's simple geometry. With it every target type goes through the same engine in the
 * sandbox (`lib/model.py` + the four patterns); there is no special case for "types without a model".
 *
 *   circle    → one `cylinder` link, `orbit` surface around it
 *   rectangle → one `box` link, `face_grid` surfaces on its four sides and its top
 *
 * Frame: origin at the footprint's centre at ground level, x = East / y = North when azimFront = 0 (the
 * sandbox rotates it by each instance's azimFront). A rectangle's `width` runs along x and `length` along y,
 * the same convention as `lib/world.py`'s simple geometry.
 *
 * The YAML is written from a template on purpose: the shape is fixed and tiny, and it keeps the tool free of
 * a YAML dependency. Values go in as numbers, never as expressions, so nothing in them can collide with the
 * model's keywords (`radius`, `half_width`...).
 */

export type CatalogGeometry = {
  geometry_type?: string;
  height?: number;
  dimensions?: { radius?: number; width?: number; length?: number; height?: number };
};

export const slugify = (type: string) =>
  type.replace(/[^A-Za-z0-9]+/g, "_").replace(/^_|_$/g, "").toLowerCase();

const num = (value: unknown) => (typeof value === "number" && Number.isFinite(value) && value > 0 ? value : null);

/** The model's YAML text, or an error explaining which catalog field is missing. */
export function synthesizeModel(
  type: string,
  geometry: CatalogGeometry | null | undefined,
): { yaml: string } | { error: string } {
  const kind = geometry?.geometry_type;
  const dims = geometry?.dimensions ?? {};
  const height = num(dims.height ?? geometry?.height);
  if (height === null) return { error: `catalog geometry of "${type}" has no positive height` };

  const slug = slugify(type);
  const header = [
    `# Generated by prepare_mission_input: "${type}" has no definitionYaml in the GCS catalog.`,
    "# Built from the catalog's simple geometry only — no parts, zones or features beyond this envelope.",
    "format: insem/0.2",
    "asset:",
    `  id: ${JSON.stringify(slug)}`,
    `  class: ${JSON.stringify(slug)}`,
    `  name: ${JSON.stringify(type)}`,
    `  description: ${JSON.stringify("Minimal model generated from the catalog geometry")}`,
    "  generated: true",
  ];

  if (kind === "circle") {
    const radius = num(dims.radius);
    if (radius === null) return { error: `catalog geometry of "${type}" is a circle without a positive radius` };
    return {
      yaml: [
        ...header,
        "parameters:",
        `  radius: ${radius}`,
        `  height: ${height}`,
        "links:",
        "  - name: body",
        `    class: ${JSON.stringify(slug)}`,
        "    joint: {type: fixed}",
        "    geometry:",
        `      - {id: shell, type: cylinder, radius: ${radius}, length: ${height}}`,
        "    inspection:",
        "      surfaces:",
        "        - {id: shell, pattern: orbit, prim: shell, offset: radius, description: Lateral surface}",
        "      zones:",
        "        base: {range: [0.0, 0.33]}",
        "        middle: {range: [0.33, 0.66]}",
        "        top: {range: [0.66, 1.0]}",
        "",
      ].join("\n"),
    };
  }

  if (kind === "rectangle") {
    const width = num(dims.width);
    const length = num(dims.length);
    if (width === null || length === null) {
      return { error: `catalog geometry of "${type}" is a rectangle without positive width and length` };
    }
    return {
      yaml: [
        ...header,
        "parameters:",
        `  width: ${width}`,
        `  length: ${length}`,
        `  height: ${height}`,
        "links:",
        "  - name: body",
        `    class: ${JSON.stringify(slug)}`,
        "    joint: {type: fixed}",
        "    geometry:",
        `      - {id: box, type: box, size: [${width}, ${length}, ${height}], pose: {xyz: [0, 0, ${height / 2}]}}`,
        "    inspection:",
        "      surfaces:",
        "        - {id: front, pattern: face_grid, prim: box, face: \"+y\", description: Face towards azimFront}",
        "        - {id: back, pattern: face_grid, prim: box, face: \"-y\"}",
        "        - {id: right, pattern: face_grid, prim: box, face: \"+x\"}",
        "        - {id: left, pattern: face_grid, prim: box, face: \"-x\"}",
        "        - {id: top, pattern: face_grid, prim: box, face: \"+z\"}",
        "",
      ].join("\n"),
    };
  }

  return { error: `catalog geometry of "${type}" has unsupported geometry_type ${JSON.stringify(kind)}` };
}
